export const initialSampleTask = {
    countTaskList: [
        {
            keyList: 0,
            countTask: 3,
        },
        {
            keyList: 1,
            countTask: 1,
        },
        {
            keyList: 2,
            countTask: 0,
        },
        {
            keyList: 3,
            countTask: 0,
        },
        {
            keyList: 4,
            countTask: 0,
        }
    ],
    listTask: [
        {
            keyList: 0,
            keyTask: 0,
            nameTask: 'Completed Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: false,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: false,
            isChecked: false,
        },
        {
            keyList: 0,
            keyTask: 1,
            nameTask: 'New Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: true,
            isChecked: false,
        },
        {
            keyList: 0,
            keyTask: 2,
            nameTask: 'Sample Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'Medium',
            isNew: false,
            isChecked: false,
        },
        {
            keyList: 0,
            keyTask: 3,
            nameTask: 'Go to gym',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'High',
            isNew: false,
            isChecked: false,
        },
    
        {
            keyList: 1,
            keyTask: 0,
            nameTask: 'Completed Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: false,
            isChecked: false,
        },
        {
            keyList: 1,
            keyTask: 1,
            nameTask: 'NotCompleted Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: false,
            isChecked: false,
        },
    
        {
            keyList: 2,
            keyTask: 0,
            nameTask: 'Sample Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: false,
            isChecked: false,
        },
    
        {
            keyList: 3,
            keyTask: 0,
            nameTask: 'Sample Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: false,
            isChecked: false,
        },
    
        {
            keyList: 4,
            keyTask: 0,
            nameTask: 'Sample Reminder',
            noteTask: '',
            dateTask: '12/05/2024',
            useDateTask: true,
            minuteTask: 5,
            hourTask: 12,
            useTimeTask: false,
            useTagsTask: true,
            useLocationTask: false,
            useMessTask: false,
            useFlagTask: false,
            urlTask: '',
            priorityTask: 'None',
            isNew: false,
            isChecked: false,
        },
    ]
}